Capstone-GH/capstone-wb

package-lock.json
package.json
server/api/index.js
server/api/projects.js
server/db/db.js
server/db/models/index.js
server/db/models/project.js
server/db/models/user.js
server/index.js

refactor: replace pg and Sequelize with MDB and Mongoose

---

client/components/line.js
client/components/navbar.js
client/components/whiteboard.js

---
Pen tool assist is working

feat: whiteboard tool pen working

---

client/components/navbar.js
server/auth/index.js
server/db/models/index.js
server/db/models/user.js
server/index.js

refactor: adjusted user model and auth routes to work with mongodb

---

client/components/line.js
client/components/redrawutils.js
client/components/whiteboard.js
client/store/index.js
client/store/linePoints.js

---
Additional feature on whiteboard.js

refactor: additional features on whiteboard.js

---

.travis.yml

Travis: activate deployment

---

client/components/redrawutils.js
client/components/saved-boards.js
client/components/whiteboard.js
client/routes.js
client/store/canvasData.js
server/api/projects.js

save board

---

client/components/codeEditor.js
client/components/navbar.js
client/routes.js
package-lock.json
package.json

feat: working code editor

---

client/components/navbar.js
client/components/redrawutils.js
client/components/whiteboard.js
client/routes.js
client/store/canvasData.js
server/api/projects.js
server/db/models/project.js

feat: ability to save and reload basic drawings

---

client/components/codeEditor.js
client/components/whiteboard.js
client/routes.js
client/store/canvasData.js
package-lock.json
package.json
server/api/projects.js

---
Bug: code editor does not save

Save editor

---

client/components/codeEditor.js
client/components/project.js
client/components/saved-boards.js
client/components/whiteboard.js
client/routes.js
client/store/canvasData.js
public/style.css

Refactor: moved whiteboard and code editor under one component

---

client/components/codeEditor.js
client/components/navbar.js
client/components/project.js
client/components/saved-boards.js
client/components/whiteboard.js
client/routes.js
client/store/canvasData.js
public/style.css
server/auth/index.js
server/db/models/user.js

Workspace styling cleanup

---

client/components/project.js
client/store/canvasData.js
server/api/projects.js
server/auth/index.js

fix: signup error handling and new board save

---

client/components/project.js
client/socket.js
client/store/canvasData.js
server/socket/index.js

feat: socket room connection and share link

---

client/components/line.js
client/components/project.js
client/components/toolbar.js
client/components/whiteboard.js
package-lock.json
package.json
public/index.html
public/style.css

Added Toolbar Component

---

client/components/shapes/circle.js
client/components/shapes/rectangle.js
client/components/toolbar.js
client/components/whiteboard.js

---
Circle and rectangle tool assist

feat: circle and rect tool assist

---

client/components/chatBox.js
client/components/line.js
client/components/navbar.js
client/components/project.js
client/components/redrawutils.js
client/components/whiteboard.js
client/store/canvasData.js
server/api/projects.js

Line Data Update

---

client/components/auth-form.js
client/components/index.js
client/components/login-form.js
client/components/new.js
client/components/signup-form.js
package-lock.json
package.json
server/auth/index.js

login and sign up

---

client/components/project.js
public/style.css

style: project title bar and buttons

---

client/components/line.js
client/socket.js
server/socket/index.js

Fix: line collab bug fix

---

client/components/project.js
client/components/whiteboard.js
public/style.css

Split screen merge

---

client/components/codeEditor.js
client/components/line.js
client/components/project.js
client/components/toolbar.js
client/components/whiteboard.js
client/store/index.js
client/store/toolbar.js
public/style.css

Updated drawer toolbar to static toolbar with right-click additional options

Toolbar refactor

---

client/app.js
client/components/auth-form.js
client/components/auth-modal.js
client/components/login-form.js
client/components/project.js
client/components/shapes/line.js
client/components/signup-form.js
client/store/canvasData.js
client/store/user.js
server/api/projects.js

* Prompts login on save
* Does not error on share if not logged in
* Removes board from userBoards array on board delete

UI Cleanup

---

client/components/project.js
client/components/shapes/text.js
client/components/shapes/tree.js
client/components/textNode.js
client/components/toolbar.js
client/components/whiteboard.js
client/socket.js
client/store/canvasData.js
package-lock.json
package.json
server/api/projects.js
server/socket/index.js

- Text updates
- Text saves & rerenders
- Text is connected via sockets
GO TEAM!

Working Text Feature

---

client/components/erase.js
client/components/landingPage.js
client/components/navbar.js
client/components/shapes/arrow.js
client/components/shapes/circle.js
client/components/shapes/line.js
client/components/shapes/rectangle.js
client/components/shapes/text.js
client/components/toolbar.js
client/components/whiteboard.js
client/routes.js
client/socket.js
client/store/index.js
client/store/user.js

refactor: code refactoring

---

public/style.css

This seems to fix the issue where text in the editor starts to scroll off the screen as you're typing a long line of code

code editor adjust

---

README.md
client/routes.js
package-lock.json
package.json
server/db/models/user.spec.js

---
changes in the readme section

Documentations
